/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.ac.bg.fon.ps.view.form;

import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import rs.ac.bg.fon.ps.controller.Controller;

/**
 *
 * @author Katarina
 */
public class FrmMain extends javax.swing.JFrame {

    /**
     * Creates new form FrmMain
     */
    public FrmMain() {
        initComponents();
        prepareForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblImage = new javax.swing.JLabel();
        menuMain = new javax.swing.JMenuBar();
        menuProduct = new javax.swing.JMenu();
        miProductNew = new javax.swing.JMenuItem();
        miProductSearch = new javax.swing.JMenuItem();
        menuAbout = new javax.swing.JMenu();
        menuUser = new javax.swing.JMenu();
        miLogOut = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Maestral");
        setMinimumSize(new java.awt.Dimension(1048, 800));

        lblImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/ac/bg/fon/ps/view/image/teddy.png"))); // NOI18N
        lblImage.setMinimumSize(new java.awt.Dimension(0, 0));

        menuMain.setPreferredSize(new java.awt.Dimension(125, 40));

        menuProduct.setForeground(new java.awt.Color(2, 26, 126));
        menuProduct.setText("Product");
        menuProduct.setFont(new java.awt.Font("Bauhaus 93", 0, 24)); // NOI18N

        miProductNew.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        miProductNew.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        miProductNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/ac/bg/fon/ps/view/image/plus.png"))); // NOI18N
        miProductNew.setText("New");
        miProductNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miProductNewActionPerformed(evt);
            }
        });
        menuProduct.add(miProductNew);

        miProductSearch.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        miProductSearch.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        miProductSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/ac/bg/fon/ps/view/image/search.png"))); // NOI18N
        miProductSearch.setText("Search");
        miProductSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miProductSearchActionPerformed(evt);
            }
        });
        menuProduct.add(miProductSearch);

        menuMain.add(menuProduct);

        menuAbout.setForeground(new java.awt.Color(2, 26, 126));
        menuAbout.setText("About");
        menuAbout.setFont(new java.awt.Font("Bauhaus 93", 0, 24)); // NOI18N
        menuMain.add(menuAbout);

        menuUser.setForeground(new java.awt.Color(2, 26, 126));
        menuUser.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        miLogOut.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        miLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/ac/bg/fon/ps/view/image/logout.png"))); // NOI18N
        miLogOut.setText("Log out");
        miLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miLogOutActionPerformed(evt);
            }
        });
        menuUser.add(miLogOut);

        menuMain.add(menuUser);

        setJMenuBar(menuMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImage, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImage, javax.swing.GroupLayout.DEFAULT_SIZE, 787, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miProductNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miProductNewActionPerformed
        try {
            JDialog dialog = new FrmProduct(this, true);
            dialog.setLocationRelativeTo(this);
            dialog.setVisible(true);
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error occured. View initialisation failed.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_miProductNewActionPerformed

    private void miLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miLogOutActionPerformed
        try {
            Controller.getInstance().setCurrentUser(null);
            this.dispose();
            JOptionPane.showMessageDialog(this, "You've been successfully logged out.", "Log out", JOptionPane.INFORMATION_MESSAGE);
            new FrmLogIn().setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error occured. Log out failed.", "Log out error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_miLogOutActionPerformed

    private void miProductSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miProductSearchActionPerformed
        try {
            JDialog dialog = new FrmSearchProducts(this, true);
            dialog.setLocationRelativeTo(this);
            dialog.setVisible(true);
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error occured. View initialisation failed.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_miProductSearchActionPerformed

    private void prepareForm() {
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setLocationRelativeTo(null);
        getContentPane().setBackground(Color.WHITE);
        menuUser.setText(Controller.getInstance().getCurrentUser().getUsername());
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblImage;
    private javax.swing.JMenu menuAbout;
    private javax.swing.JMenuBar menuMain;
    private javax.swing.JMenu menuProduct;
    private javax.swing.JMenu menuUser;
    private javax.swing.JMenuItem miLogOut;
    private javax.swing.JMenuItem miProductNew;
    private javax.swing.JMenuItem miProductSearch;
    // End of variables declaration//GEN-END:variables
}
